services:
  portfolio-backend:
    image: "portfolio-backend"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "50223:3000"
    env_file:
      - backend.env
    restart: unless-stopped
